config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  authenticated :user do
    root to: 'dashboard#feed', as: 'user_root'
  end
  unauthenticated do
    root to: 'home#index'
  end
  resources :courses, path: 'cursos', only: [:index, :show]
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @user = User.new
  end
end

app/views/home/index.html.erb
<div class="row">
  <div class="col-xs-12 home-logo">
    <%= image_tag "home_logo.png", class: "img-responsive" %>
  </div>

  <div class="col-xs-12 text-center home-message">
    <h1> <%= t('content.home_msg_1') %> </h1>
  </div>
</div>

<div class="row-space-2"></div>

<div class="row text-center">
  <div class="col-lg-4 col-lg-offset-4 col-md-5 col-md-offset-4 col-sm-6 col-sm-offset-3">
    <%= simple_form_for(@user, as: 'user', url: session_path('user')) do |f| %>

      <div class="input-group">
        <span class="input-group-addon">
          <i class="fa fa-user"></i>
        </span>
        <%= f.input :email, label_html: { class: 'sr-only' } %>
      </div>

      <div class="input-group">
        <span class="input-group-addon">
          <i class="fa fa-lock"></i>
        </span>

        <%= f.input :password, label_html: { class: 'sr-only' } %>
        <span class="input-group-addon hidden-xs help">
          <div class="gde-tooltip"
               data-toggle="tooltip"
               data-placement="right"
               data-trigger="manual"
               data-title="<%= t('content.password_tooltip') %>">?</div>
        </span>
      </div>

      <%= f.button :submit, class: 'btn btn-lg btn-block btn-login' %>
    <% end %>

    <a href="#"><%= t('forms.dac_login') %></a>
    <%= link_to t('forms.forgot_password'), new_password_path('user') %>
  </div>
</div>
<div class="row-space-2"></div>

<div id="home_news" class="row hidden-xs text-center">
  <div class="col-lg-12 col-md-12 col-sm-12">
    <h2><%= t('content.home_msg_2') %></h2>
  </div>

  <div class="col-lg-2 col-lg-offset-2 col-md-3 col-sm-3">
    <span class="fa-stack fa-lg">
      <i class="fa fa-circle fa-stack-2x"></i>
      <i class="fa fa-graduation-cap fa-stack-1x fa-inverse"></i>
    </span>

    <h4><%= t('content.home_news_title_1') %></h4>
    <p><%= t('content.home_news_text_1') %></p>
  </div>

  <div class="col-lg-2 col-md-3 col-sm-3">
     <span class="fa-stack fa-lg">
      <i class="fa fa-circle fa-stack-2x"></i>
      <i class="fa fa-cutlery fa-stack-1x fa-inverse"></i>
    </span>

    <h4><%= t('content.home_news_title_2') %></h4>
    <p><%= t('content.home_news_text_2') %></p>
  </div>

  <div class="col-lg-2 col-md-3 col-sm-3">
     <span class="fa-stack fa-lg">
      <i class="fa fa-circle fa-stack-2x"></i>
      <i class="fa fa-users fa-stack-1x fa-inverse"></i>
    </span>

    <h4><%= t('content.home_news_title_3') %></h4>
    <p><%= t('content.home_news_text_3') %></p>
  </div>

  <div class="col-lg-2 col-md-3 col-sm-3">
    <span class="fa-stack fa-lg">
      <i class="fa fa-circle fa-stack-2x"></i>
      <i class="fa fa-university fa-stack-1x fa-inverse"></i>
    </span>

    <h4><%= t('content.home_news_title_4') %></h4>
    <p><%= t('content.home_news_text_4') %></p>
  </div>
</div>