config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  authenticated :user do
    root to: 'dashboard#feed', as: 'user_root'
  end
  unauthenticated do
    root to: 'home#index'
  end
  resources :courses, path: 'cursos', only: [:index, :show]
end

app/views/layouts/_footer.html.erb
<footer class="text-center">
  <div class="footer-top container-fluid">
    <%= t('content.footer_message') %>
  </div>

  <div class="footer-bottom container-fluid">
    <strong><%= t('content.all_rights_reserved') %> 2007 - <%= Time.now.year %></strong>
  </div>
</footer>

app/views/layouts/_left_sidebar.html.erb
<ul class="left-sidebar-menu">
  <li class="title">
    <%= t('sidebar.academic') %>
  </li>

  <li class="active">
    <%= link_to '#' do %>
      <i class="li_eye"></i>
      <span><%= t('sidebar.integralization') %></span>
    <% end %>
  </li>

  <li>
    <%= link_to courses_path do %>
      <i class="li_study"></i>
      <span>Disciplinas (TESTE)</span>
    <% end %>
  </li>

  <li>
    <%= link_to '#' do %>
      <i class="li_food"></i>
      <span><%= t('sidebar.week_menu') %></span>
    <% end %>
  </li>

  <li>
    <%= link_to '#' do %>
      <i class="li_like"></i>
      <span><%= t('sidebar.rate_professors') %></span>
    <% end %>
  </li>

  <li>
    <%= link_to '#' do %>
      <i class="li_study"></i>
      <span><%= t('sidebar.my_courses') %></span>
    <% end %>
  </li>

  <li>
    <%= link_to '#' do %>
      <i class="li_location"></i>
      <span><%= t('sidebar.campus_map') %></span>
    <% end %>
  </li>

  <li>
    <%= link_to '#' do %>
      <i class="li_lock"></i>
      <span><%= t('sidebar.plan_courses') %></span>
    <% end %>
  </li>

  <li class="title">
    <%= t('sidebar.social') %>
  </li>

  <li class="title">
    <%= t('sidebar.help') %>
  </li>

</ul>

app/views/layouts/_right_sidebar.html.erb
<ul class="right-sidebar-menu">
  <li>
    <%= link_to '#' do %>
      <%= image_tag 'http://placehold.it/43x43', class: 'pull-left', width: '43', height: '43' %>
      <span class="status online">&bull;</span>
      Xico Metranca dos nome gigante
    <% end %>
  </li>
  <li>
    <%= link_to '#' do %>
      <%= image_tag 'http://placehold.it/43x43', class: 'pull-left', width: '43', height: '43' %>
      <span class="status busy">&bull;</span>
      Alcebíades
    <% end %>
  </li>
  <li>
    <%= link_to '#' do %>
      <%= image_tag 'http://placehold.it/43x43', class: 'pull-left', width: '43', height: '43' %>
      <span class="status offline">&bull;</span>
      Jeremias
    <% end %>
  </li>
</ul>

app/views/layouts/_sidebar.html.erb
<ul class="sidebar-menu" id="nav-accordion">
  <li class="title">
    <%= t('sidebar.academic') %>
  </li>

  <li class="active">
    <%= link_to '#' do %>
      <i class="li_eye"></i>
      <span><%= t('sidebar.integralization') %></span>
    <% end %>
  </li>

  <li>
    <%= link_to courses_path do %>
      <i class="li_study"></i>
      <span>Disciplinas (TESTE)</span>
    <% end %>
  </li>

  <li>
    <%= link_to '#' do %>
      <i class="li_food"></i>
      <span><%= t('sidebar.week_menu') %></span>
    <% end %>
  </li>

  <li>
    <%= link_to '#' do %>
      <i class="li_like"></i>
      <span><%= t('sidebar.rate_professors') %></span>
    <% end %>
  </li>

  <li>
    <%= link_to '#' do %>
      <i class="li_study"></i>
      <span><%= t('sidebar.my_courses') %></span>
    <% end %>
  </li>

  <li>
    <%= link_to '#' do %>
      <i class="li_location"></i>
      <span><%= t('sidebar.campus_map') %></span>
    <% end %>
  </li>

  <li>
    <%= link_to '#' do %>
      <i class="li_lock"></i>
      <span><%= t('sidebar.plan_courses') %></span>
    <% end %>
  </li>

  <li class="title">
    <%= t('sidebar.social') %>
  </li>

  <li class="title">
    <%= t('sidebar.help') %>
  </li>

</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GDE</title>
    <link href='http://fonts.googleapis.com/css?family=PT+Sans|Roboto:100' rel='stylesheet' type='text/css'>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <div class="container-fluid">
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
    <%= javascript_include_tag 'application' %>
  </body>
</html>

app/views/layouts/user.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GDE</title>
    <%= stylesheet_link_tag 'http://fonts.googleapis.com/css?family=PT+Sans|Roboto:100' %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <section class="container-fluid">
      <!-- Header -->
      <header class="header row">
        <div class="header-left col-lg-2 col-sm-3">
          <%= link_to image_tag("home_logo.png", width: '72', height: '72'), root_path %>
        </div>

        <div class="header-center col-lg-8 col-sm-9 no-padding">
          <div class="nav-user">
            <%= image_tag 'http://placehold.it/43x43', class: 'pull-left' %>
            <div class="nav-user-info">
              <span class="nav-user-name"><%= "Pota Beranizo" %></span>
              <span class="nav-user-notifications"><%= "Você tem x notificações" %></span>
            </div>
            <i class="nav-user-icon fa fa-caret-down"></i>
          </div>
        </div>

        <div class="header-right col-lg-2 visible-lg">
          <div class="input-group no-border-radius">
            <input type="text" class="form-control no-border-radius" placeholder="Buscar amigos...">
            <span class="input-group-addon no-border-radius"><i class="fa fa-search"></i></span>
          </div>
        </div>
      </header>

      <section class="row">
        <!-- Sidebar -->
        <aside id="left_sidebar" class="col-lg-2 col-sm-3 no-padding" role="navigation">
          <%= render 'layouts/left_sidebar' %>
        </aside>

        <!-- Main Content -->
        <main id="main-content" class="col-lg-8 col-sm-9">
          <%= yield %>
        </main>

        <!-- Right sidebar -->
        <aside id="right_sidebar" class="col-lg-2 visible-lg no-padding">
          <%= render 'layouts/right_sidebar' %>
        </aside>
      </section>
    </section>

    <%= render 'layouts/footer' %>
    <%= javascript_include_tag 'application' %>
  </body>
</html>

app/views/layouts/visitor.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GDE</title>
    <%= stylesheet_link_tag 'http://fonts.googleapis.com/css?family=PT+Sans|Roboto:100' %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <div class="container-fluid">
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
    <%= javascript_include_tag 'application' %>
  </body>
</html>